FROM node:16-alpine

WORKDIR /app

COPY package*.json ./
COPY . .

RUN yarn install

RUN yarn build

FROM nginx:alpine

COPY --from=0 /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 5000

CMD ["nginx", "-g", "daemon off;"]