version: '3'

services:
  BE_TCDL:
    image: hungwap375/mystore:BE_TCDL
    network_mode: 'nginx-proxy'
    container_name: BE_TCDL
    ports:
      - '4000:4000'
    environment:
      - VIRTUAL_HOST=api.tcdl.chuhung.com
      - VIRTUAL_PORT=4000
      - LETSENCRYPT_HOST=api.tcdl.chuhung.com
      - PORT_TCDL = 4000;
      - DB_URL_TCDL = mongodb://TuanHung:Hung532002@103.14.48.14:3701/Medicine?authMechanism=DEFAULT;
      - HOSTNAME = https://api.tcdl.chuhung.com;

  FE_TCDL:
    image: hungwap375/mystore:FE_TCDL
    network_mode: 'nginx-proxy'
    container_name: FE_TCDL
    ports:
      - '5000:5000'
    environment:
      - VIRTUAL_HOST=tcdl.chuhung.com
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=tcdl.chuhung.com
      - VITE_BACKEND_URL = https://api.tcdl.chuhung.com/api/;
